version: '2'
services:
  homeless-service:
    environment:
# why are these needed?
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - CONFIG_BUCKET=${CONFIG_BUCKET}
#    
    - PROJ_SETTINGS_DIR=${PROJ_SETTINGS_DIR}
    - DEPLOY_TARGET=${DEPLOY_TARGET}
    - CONFIG_BUCKET=assign9-config/integration
    build: .
    image: "${DOCKER_REPO}/${DOCKER_IMAGE}"
    command: /code/docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
